iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N

# Site
title:              Vegan or not Vegan
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "/vegan_or_not" # the subpath of your site, e.g. /blog
url: "https://barnabegeffroy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Paris, France
phone:              xxxxxxxxxxx
email:              barnabe.geffroy@psl.eu # change this to your email to receive free emails for your contact submissions via Slapform.com





jekyll-mentions:
    base_url: https://github.com


# Build settings
theme: jekyll-theme-leaf
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
