= Construction of a Jekyll site by Travis-CI and deployment on a GitHub page

This documentation will allow you to set up an automatic deployment of your Jekyll site on a GitHub page. GitHub pages are designed to host your personal pages, your organization's pages, or your Jekyll project pages from the main branch of a GitHub repository. You must therefore always have a correct Jekyll project in the main branch of your repository to ensure that the page is built.

== Motivation

We want a tool to modify the Jekyll project without compromising the deployment of the GitHub page. For this, we will use Travis-CI. First, we will show how to build a GitHub page with a Jekyll project. Then we will establish an automatic construction of the page thanks to Travis-CI.

== Set-up for a GitHub page

To deploy your site on a GitHub page, go to the repository settings of your Jekyll project. There's a *GitHub Pages* section. In it, select *master branch* as the source. A link appears in this section looking like *https://username.github.io/repo_name/*: this is your GitHub page. But this one probably doesn't build itself, or doesn't display your Jekyll project correctly.

You need to modify your `_config.yml` and your `Gemfile` of your Jekyll project. 

* `_config.yml`:
You must complete the `baseurl` and `url` functions. You also must group all your Gems in a plugin group. You can also add the theme: minima. Look the example below.

.Sample `_config.yml` configuration file
[source,yaml]
----
---

baseurl: "/repo_name" 
url: "https://username.github.io"

---

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-gist 
----

* `Gemfile`:
If you are not comfortable with it, I advise you to read Jekyll's https://jekyllrb.com/docs/step-by-step/10-deployment/[doc] about it.

You have to remove (or comment) the `gem "jekyll" line, "~> 4.0.0"` and add `gem "github-pages", group: :jekyll_plugins`. Then put all the plugins as in the example below: 

.Sample `Gemfile` configuration file
[source,Gemfile]
----
source "https://rubygems.org"

# gem "jekyll", "~> 4.0.0"

gem "minima", "~> 2.5"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-mentions"
  gem "jekyll-gist"
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

----

This Gemfile is inspired by the one generated automatically when creating a Jekyll project (with the command `bundle exec jekyll new .`)
Look what he looks like https://github.com/barnabegeffroy/vegan_or_not/blob/build/Original_Gemfile[here] to understand the other lines.

Once this is done, do :

. `bundle update` 
. `bundle install`
. `bundle exec jekyll serve` 

The link to your local page will be in the command line and will looking like :

`Server address: http://127.0.0.1:4000/repo_name/`

If you push on your repository these changes, after a few moments, your site should build itself cleanly.

== Deployment with Travis-CI

The idea is to let Travis do automatic commits to the master branch of your repository when no errors are detected by Travis. Create a `build` branch, this is where you will push all your changes. Now we need to configure Travis so to it can push the correct changes to the master branch. 

To do this, attentively follow this very detailed **https://tonyzhangnd.github.io/2018/06/Integrating-Jekyll-and-Travis-CI.html[tutorial]** by Tony Zhang (https://github.com/oliviercailloux/tonyzhangnd.github.io/blob/master/2018/06/Integrating-Jekyll-and-Travis-CI.html[copy here]). This one, allows you to push the `_site` directory (generated by `bundle exec jekyll serve`) into the master branch of the repository in which your GitHub page is located, but it could very well be another repository, in case you don't want to show your jekyll project completely.

You should have a `.travis.yml` like this: 

.Sample `.travis.yml` configuration file
[source,yaml]
----
language: ruby

cache: bundler 

before_install: 
  - gem update bundler
  - chmod +x ./script/cibuild
install:
  - bundle install

script: ./script/cibuild

branches:
  only:
  - build

sudo: false

notifications:
  email: false
----

Note that there is a small modification compared to the tutorial :

`- chmod +x ./script/cibuild`

This allows to correctly execute the `cibuild` (called `Setup` in the tutorial but renamed and placed in a `script` directory for a Jekyll convention).

.Content `cibuild` configuration file
[source,cibuild]
----
set -e
DEPLOY_REPO="https://${MY_WEBSITE}@github.com/username/repo_name.git"
function main {
	clean
	get_current_site
	build_site
	deploy
}

function clean { 
	echo "cleaning _site folder"
	if [ -d "_site" ]; then rm -Rf _site; fi 
}

function get_current_site { 
	echo "getting latest site"
	git clone --depth 1 $DEPLOY_REPO _site 
}

function build_site { 
	echo "building site"
	bundle exec jekyll build --trace
}

function deploy {
	echo "deploying changes"

	if [ -z "$TRAVIS_PULL_REQUEST" ]; then
	    echo "except don't publish site for pull requests"
	    exit 0
	fi  

	if [ "$TRAVIS_BRANCH" != "build" ]; then
	    echo "except we should only publish the build branch. stopping here"
	    exit 0
	fi

	cd _site
	git config --global user.name "Travis CI"
    git config --global user.email username@mail.com
	git add -A
	git status
	git commit -m "Lastest site built on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to github"
	git push $DEPLOY_REPO master:master
}

main
----
